// <auto-generated />
using GamingAppPac3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingAppPac3.Migrations
{
    [DbContext(typeof(GamingAppPac3Context))]
    partial class GamingAppPac3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamingAppPractice.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GamingAppPractice.Models.Gamer", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("InGameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Gamer");
                });

            modelBuilder.Entity("GamingAppPractice.Models.Gamer_Game", b =>
                {
                    b.Property<int>("GGKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GGKey"));

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<int?>("GamerUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("GGKey");

                    b.HasIndex("GameID");

                    b.HasIndex("GamerUserID");

                    b.ToTable("Gamer_Game");
                });

            modelBuilder.Entity("GamingAppPractice.Models.Gamer_Game", b =>
                {
                    b.HasOne("GamingAppPractice.Models.Game", "Game")
                        .WithMany("Gamer_Games")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingAppPractice.Models.Gamer", "Gamer")
                        .WithMany("Gamer_Gamers")
                        .HasForeignKey("GamerUserID");

                    b.Navigation("Game");

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("GamingAppPractice.Models.Game", b =>
                {
                    b.Navigation("Gamer_Games");
                });

            modelBuilder.Entity("GamingAppPractice.Models.Gamer", b =>
                {
                    b.Navigation("Gamer_Gamers");
                });
#pragma warning restore 612, 618
        }
    }
}
